    
db.clientes.insertMany([

{_id: 01,
Nombre: "Fran",
Servicio: "Esmalte permanente",
Precio: 10,
Pago:{
Pago_Bizum: false ,
Pago_Efectivo: true},
Dirección: "Calle Conde 7",
Localidad: "El Viso del Alcor",
Número_teléfono: 614032883,
Genero: "M",
},

{_id: 02,
    Nombre: "Fran",
    Servicio: " Cejas",
    Precio: 3 ,
    Pago:{
    Pago_Bizum: false ,
    Pago_Efectivo: true},
    Dirección: "Calle Conde 7",
    Localidad: "El Viso del Alcor",
    Número_teléfono: 614032883,
    Genero: "M",
},
    
{
_id: 03,
Nombre:"Edu" ,
Servicio: "Esmalte permanente",
Precio: 10,
Pago:{
Pago_Bizum: false ,
Pago_Efectivo: true},
Dirección: "Calle Lora del Rio 29",
Número_teléfono: 679205187,
Localidad: "El Viso del Alcor",
Genero: "M",
},
{
    _id: 04,
    Nombre:"Edu" ,
    Servicio: " Cejas",
    Precio: 3 ,
    Pago:{
    Pago_Bizum: false ,
    Pago_Efectivo: true},
    Dirección: "Calle Lora del Rio 29",
    Número_teléfono: 679205187,
    Localidad: "El Viso del Alcor",
    Genero: "M",
    },
{_id: 05,
Nombre: "Tamara",
Servicio: "Porcelana ",
Precio:20,
Pago:{
Pago_Bizum: false ,
Pago_Efectivo: true},
Dirección: "Calle Corrales n° 12" ,
Localidad: "Mairena del Alcor" ,
Número_teléfono: 622490638,
Genero: "F"
},
{_id: 06,
    Nombre: "Tamara",
    Servicio: "cejas",
    Precio: 4,
    Pago:{
    Pago_Bizum: false ,
    Pago_Efectivo: true},
    Dirección: "Calle Corrales n° 12" ,
    Localidad: "Mairena del Alcor" ,
    Número_teléfono: 622490638,
    Genero: "F"
    },
    {_id: 07,
        Nombre: "Tamara",
        Servicio: "labio",
        Precio: 4,
        Pago:{
        Pago_Bizum: false ,
        Pago_Efectivo: true},
        Dirección: "Calle Corrales n° 12" ,
        Localidad: "Mairena del Alcor" ,
        Número_teléfono: 622490638,
        Genero: "F"
        },
{_id: 08,
Nombre: "Ángela", 
Servicio: "Esmalte permanente",
Precio: 10, 
Pago:{
Pago_Bizum: false ,
Pago_Efectivo: true},
Dirección: "Calle Real 18",
Número_teléfono: 672910439,
Localidad: "El Viso del Alcor",
Genero: "F",
},
{_id: 09,
    Nombre: "Ángela", 
    Servicio: "Cejas ",
    Precio:  4,
    Pago:{
    Pago_Bizum: false ,
    Pago_Efectivo: true},
    Dirección: "Calle Real 18",
    Número_teléfono: 672910439,
    Localidad: "El Viso del Alcor",
    Genero: "F",
    },
    {_id: 10,
        Nombre: "Ángela", 
        Servicio: " Labio",
        Precio: 4,
        Pago:{
        Pago_Bizum: false ,
        Pago_Efectivo: true},
        Dirección: "Calle Real 18",
        Número_teléfono: 672910439,
        Localidad: "El Viso del Alcor",
        Genero: "F",
        },
{_id: 11,
Nombre: "Carolina Vecina",
Servicio: "Porcelana",
Precio: 20,
Pago:{
Pago_Bizum: true,
Pago_Efectivo: false},
Dirección: "Calle Manuel de los Santos" ,
Número_teléfono: 658010398,
Localidad: "El Viso del Alcor" ,
Genero: "F",
},
{_id: 12,
Nombre: "Tita Ana",
Servicio: "Esmalte permanente",
Precio: 10,
Pago:{
Pago_Bizum: false ,
Pago_Efectivo: true},
Dirección: "Calle Sevilla 87",
Número_teléfono:608002345,
Localidad: "El Viso del Alcor",
Genero: "F",
},
{_id: 13,
Nombre: "Salud Escribano",
Servicio: "Porcelana",
Precio:  20,
Pago:{
Pago_Bizum: false ,
Pago_Efectivo: true},
Dirección:"Calle La Muela  5",
Número_teléfono: 654802817,
Localidad: "El Viso del Alcor",
Genero: "F",
},
{_id: 14,
Nombre: "Luisa del Pilar",
Servicio: "Esmalte permanente",
Precio: 10,
Pago:{
Pago_Bizum: true,
Pago_Efectivo: false},
Dirección: "Calle Feria 55",
Número_teléfono: 611730634,
Localidad: "El Viso del Alcor",
Genero: "F",
},
{_id: 15,
Nombre: "Carla",
Servicio: "Ceja ",
Precio: 4,
Pago:{
    Pago_Bizum: true,
    Pago_Efectivo: false},
Dirección: "Calle Sol 33",
Número_teléfono: 655490120,
Localidad: "El Viso del Alcor",
Genero: "F",
},
{_id: 16,
    Nombre: "Carla",
    Servicio: "labio",
    Precio: 4,
    Pago:{
        Pago_Bizum: true,
        Pago_Efectivo: false},
    Dirección: "Calle Sol 33",
    Número_teléfono: 655490120,
    Localidad: "El Viso del Alcor",
    Genero: "F",
    },
{_id: 17,
Nombre: "Pilar",
Servicio: "Porcelana ",
Precio:20, 
Pago:{
    Pago_Bizum: true,
    Pago_Efectivo: false},
Dirección: "Calle Guadalete 48",
Número_teléfono: 765030918,
Localidad: "Mairena del Alcor",
Genero: "F"
},
{_id: 18,
    Nombre: "Pilar",
    Servicio: "cejas con hilo",
    Precio: 5,
    Pago:{
        Pago_Bizum: true,
        Pago_Efectivo: false},
    Dirección: "Calle Guadalete 48",
    Número_teléfono: 765030918,
    Localidad: "Mairena del Alcor",
    Genero: "F"
    },
{_id: 19,
Nombre: "Ángela",
Servicio: "Ceja",
Precio: 4,
Pago:{
    Pago_Bizum: false,
    Pago_Efectivo:true },
Dirección: "Calle Paradas 5",
Número_teléfono : 634810975,
Localidad: "El Viso del Alcor",
Genero: "F"
},
{_id: 20,
Nombre: "Angélica",
Servicio: "Esmalte permanente",
Precio:  10,
Pago:{
    Pago_Bizum: false,
    Pago_Efectivo:true },
Dirección: "Calle Estepa 82",
Número_teléfono: 729047146,
Localidad: "El Viso del Alcor",
Genero: "F"
},
{_id: 21,
Nombre:"Brenda",
Servicio:"Porcelana",
Precio:  20, 
Pago:{
    Pago_Bizum: true,
    Pago_Efectivo: false},
Dirección: "calle Doctor Fleming 28",
Número_teléfono:665341210,
Localidad: "El Viso del Alcor",
Genero: "F"
},
{_id: 22,
Nombre: "Virginia",
Servicio: "Esmalte permanente",
Precio:  10,
Pago:{
    Pago_Bizum: false,
    Pago_Efectivo:true },
Dirección: "Calle Tocina 15",
Número_teléfono: 629478091,
Localidad: "El Viso del Alcor",
Genero: "F"
}
]
)




db.proveedores.insertMany(
[
{
_id: 000, 
CIF: "B55284996",
Proveedor: "Manicura24",
Producto: "Esmalte permanente Vintage Rose",
Categoría: "Esmalte de uña",
Cantidad: 1,
Precioporunidad: 7.75,
Servicio:  ["Esmalte permanente", "Porcelana"],
Direccion: "Avda de França 22",
Telefono: 872987071 ,
Email: "info@manicura24.com",
vende_online: true,
fecha_compra: ISODate("2020-04-01T08:10:00Z"),
fecha_entrega: ISODate("2020-04-02T08:11:00Z")
},
{
_id:001,
CIF: "B55284996",
Proveedor: "Manicura24",
Producto: "Polvo acrílico Cover Peach (60g)",
Categoría: "Porcelana",
Cantidad: 1,
Precioporunidad: 9.20,
Servicio: ["Porcelana","Practica de Diseño"],
Direccion: "Avda de França 22",
Telefono: 872987071 ,
Email: "info@manicura24.com",
vende_online: true,
fecha_compra: ISODate("2020-05-11T08:08:00Z"),
fecha_entrega: ISODate("2020-05-12T08:09:00Z")
},
{
_id:002,
CIF: "B55284996",
Proveedor: "Manicura 24",
Producto: "Líquido Acrílico (250ml)",
Categoría: "Porcelana",
Cantidad: 1,
Precioporunidad: 10.00,
Servicio: ["Porcelana","Diseño"],
Direccion: "Avda de França 22",
Telefono: 872987071 ,
Email: "info@manicura24.com",
vende_online: true,
fecha_compra: ISODate("2021-04-10T08:13:12Z"),
fecha_entrega: ISODate("2021-04-11T08:14:00Z")
},
{
_id:003,
CIF: "B55284996",
Proveedor: "Manicura24",
Producto: "Nailprep (10ml)",
Categoría: "Preparado de uña",
Cantidad: 2,
Precioporunidad: 3.95,
Servicio:  ["Esmalte permanente", "Porcelana"],
Direccion: "Avda de França 22",
Telefono: 872987071 ,
Email: "info@manicura24.com",
vende_online: true,
fecha_compra: ISODate("2021-04-01T08:00:00Z"),
fecha_entrega: ISODate("2021-04-01T08:10:00Z")
},
{
_id:004,
CIF: "B55284996",
Proveedor: "Manicura24",
Producto: "Moldes Rana (500 unidades)",
Categoría: ["Porcelana","Diseño"],
Cantidad: 1,
Precioporunidad: 9.95,
Servicio: "Porcelana",
Direccion: "Avda de França 22",
Telefono: 872987071 ,
Email: "info@manicura24.com",
vende_online: true,
fecha_compra: ISODate("2022-01-01T08:00:00Z"),
fecha_entrega: ISODate("2022-01-02T08:00:00Z")
},
{
_id:005,
CIF: "B55284996",
Proveedor: "Manicura24", 
Producto: "120 tips Stiletto Nailart",
Categoría: "Diseño",
Cantidad: 1,
Precioporunidad: 5.99,
Servicio: ["Diseño", "Esmalte permanente", "Porcelana"],
Direccion: "Avda de França 22",
Telefono: 872987071 ,
Email: "info@manicura24.com",
vende_online: true,
fecha_compra: ISODate("2022-02-24T08:00:00Z"),
fecha_entrega: ISODate("2022-02-25T08:00:00Z")
},
{
_id:006,
CIF: "B55284996",
Proveedor: "Manicura24",
Producto: "Gel Sun Yellow",
Categoría: "Dibujo",
Cantidad: 1,
Precioporunidad: 4.45,
Servicio:  ["Esmalte permanente", "Porcelana"],
Direccion: "Avda de França 22",
Telefono: 872987071 ,
Email: "info@manicura24.com",
vende_online: true,
fecha_compra: ISODate("2021-12-22T08:10:00Z"),
fecha_entrega: ISODate("2021-12-23T08:10:00Z")

},
{
_id:007,
CIF: "B55284996",
Proveedor: "Manicura24",
Producto: "Gel Pure Blue",
Categoría: "Dibujo",
Cantidad: 1,
Precioporunidad: 4.45,
Servicio: ["Esmalte permanente", "Porcelana"],
Direccion: "Avda de França 22",
Telefono: 872987071 ,
Email: "info@manicura24.com",
vende_online: true,
fecha_compra: ISODate("2021-09-01T08:12:00Z"),
fecha_entrega: ISODate("2021-09-02T08:13:00Z")
},
{
_id:011,
CIF: "B55284996",
Proveedor: "Manicura24",
Producto: "Polvo Acrílico Butterfly (10gr)",
Categoría: "Porcelana",
Cantidad: 1,
Precioporunidad: 2.90,
Servicio:  ["Esmalte permanente", "Porcelana"],
Direccion: "Avda de França 22",
Telefono: 872987071 ,
Email: "info@manicura24.com",
vende_online: true,
fecha_compra: ISODate("2020-04-01T08:00:00Z"),
fecha_entrega: ISODate("2020-04-11T08:00:00Z")
}]      
)